https://storage.googleapis.com/laurencemoroney-blog.appspot.com/bbc-text.csv 
http://mlg.ucd.ie/datasets/bbc.html
#### Link to the datset

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('bbc-text.csv')

In [66]:
df.head()

text  business  entertainment  \
0  tv future in the hands of viewers with home th...       0.0            0.0   
1  worldcom boss  left books alone  former worldc...       1.0            0.0   
2  tigers wary of farrell  gamble  leicester say ...       0.0            0.0   
3  yeading face newcastle in fa cup premiership s...       0.0            0.0   
4  ocean s twelve raids box office ocean s twelve...       0.0            1.0   

   politics  sport  tech  
0       0.0    0.0   1.0  
1       0.0    0.0   0.0  
2       0.0    1.0   0.0  
3       0.0    1.0   0.0  
4       0.0    0.0   0.0

In [5]:
df1 = pd.get_dummies(df['category'])

In [6]:
df1

business  entertainment  politics  sport  tech
0            0              0         0      0     1
1            1              0         0      0     0
2            0              0         0      1     0
3            0              0         0      1     0
4            0              1         0      0     0
...        ...            ...       ...    ...   ...
2220         1              0         0      0     0
2221         0              0         1      0     0
2222         0              1         0      0     0
2223         0              0         1      0     0
2224         0              0         0      1     0

[2225 rows x 5 columns]

In [7]:
df = pd.concat([df,df1],axis=1)

In [8]:
df = df.drop('category',axis=1)

In [9]:
df

text  business  \
0     tv future in the hands of viewers with home th...         0   
1     worldcom boss  left books alone  former worldc...         1   
2     tigers wary of farrell  gamble  leicester say ...         0   
3     yeading face newcastle in fa cup premiership s...         0   
4     ocean s twelve raids box office ocean s twelve...         0   
...                                                 ...       ...   
2220  cars pull down us retail figures us retail sal...         1   
2221  kilroy unveils immigration policy ex-chatshow ...         0   
2222  rem announce new glasgow concert us band rem h...         0   
2223  how political squabbles snowball it s become c...         0   
2224  souness delight at euro progress boss graeme s...         0   

      entertainment  politics  sport  tech  
0                 0         0      0     1  
1                 0         0      0     0  
2                 0         0      1     0  
3                 0         0      1     0  
4                 1         0      0     0  
...             ...       ...    ...   ...  
2220              0         0      0     0  
2221              0         1      0     0  
2222              1         0      0     0  
2223              0         1      0     0  
2224              0         0      1     0  

[2225 rows x 6 columns]

In [11]:
stopwatch = [ "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ,"s","v"]


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
tech = []
entertainment = []
politics = []
sport = []
business = []

for i in df.drop('text',axis=1)['tech']:
    tech.append(np.float32(i))
df['tech'] = np.array(tech)  

In [14]:
for j in df.drop('text',axis=1)['entertainment']:
    entertainment.append(np.float32(j))
df['entertainment'] = np.array(entertainment)    

In [15]:
for k in df.drop('text',axis=1)['politics']:
    politics.append(np.float32(k))
df['politics'] = np.array(politics)    


In [16]:
for l in df.drop('text',axis=1)['sport']:
    sport.append(np.float32(l))
df['sport'] = np.array(sport)     

In [17]:
for m in df.drop('text',axis=1)['business']:
    business.append(np.float32(m))
df['business'] = np.array(business) 

In [18]:
y = df.drop('text',axis=1).values

In [19]:
y

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [20]:
X = df['text']

In [21]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=101)   

In [22]:
train_sentences = []
train_label = []
test_sentences = []
test_labels = []

In [23]:
for i , l in zip(X_train , y_train):
    train_sentences.append(i)
    train_label.append(l)
for j , k in zip(X_test , y_test):
    test_sentences.append(j)
    test_labels.append(k)

In [24]:
train_sentences_final = []
test_sentences_final = []

In [25]:
for s in train_sentences:    
    for w in stopwatch:
        a = " "+w+" "
        s = s.replace(a," ")
        s = s.replace("  ", " ")
    train_sentences_final.append(s)

In [26]:
for s in test_sentences:    
    for w in stopwatch:
        a = " "+w+" "
        s = s.replace(a," ")
        s = s.replace("  ", " ")
    test_sentences_final.append(s) 

In [35]:
train_label = np.float32(train_label)
test_labels = np.float32(test_labels)

In [36]:
from tensorflow.keras.preprocessing.text import Tokenizer
token = Tokenizer(num_words=10000,oov_token="<OOV>")

D:\Python\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Python\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Python\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Python\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; 

In [37]:
token.fit_on_texts(train_sentences_final)

In [38]:
word_index = token.index_word

In [39]:
train_seq = token.texts_to_sequences(train_sentences_final)

In [40]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [41]:
train_padded = pad_sequences(train_seq , maxlen=120 , truncating='post')

In [42]:
test_seq = token.texts_to_sequences(test_sentences_final)

In [43]:
test_padded = pad_sequences(test_seq , maxlen=120 , truncating='post')

In [44]:
from tensorflow.keras.models import Sequential

In [45]:
from tensorflow.keras.layers import Dense , Dropout , Embedding , GlobalAveragePooling1D

In [55]:
model = Sequential()

In [56]:
model.add(Embedding(10001 , 10 ,input_length = 120))
model.add(GlobalAveragePooling1D())
model.add(Dense(6 , activation = 'relu'))
model.add(Dense(6 , activation = 'relu'))
model.add(Dense(5 , activation = 'softmax'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [57]:
model.compile(optimizer='adam' , loss='categorical_crossentropy',metrics=['accuracy'])

In [58]:
model.fit(np.float32(train_padded) ,  train_label ,epochs=200 , batch_size=128 , validation_data=(np.float32(test_padded) , test_labels))

Train on 1557 samples, validate on 668 samples
Epoch 1/200
1557/1557 [==============================] - 1s 631us/sample - loss: 1.6084 - acc: 0.2473 - val_loss: 1.6063 - val_acc: 0.3144
Epoch 2/200
1557/1557 [==============================] - 0s 100us/sample - loss: 1.6041 - acc: 0.3340 - val_loss: 1.6015 - val_acc: 0.3608
Epoch 3/200
1557/1557 [==============================] - 0s 104us/sample - loss: 1.5980 - acc: 0.4136 - val_loss: 1.5955 - val_acc: 0.4371
Epoch 4/200
1557/1557 [==============================] - 0s 104us/sample - loss: 1.5903 - acc: 0.4271 - val_loss: 1.5876 - val_acc: 0.4326
Epoch 5/200
1557/1557 [==============================] - 0s 102us/sample - loss: 1.5804 - acc: 0.4483 - val_loss: 1.5777 - val_acc: 0.4506
Epoch 6/200
1557/1557 [==============================] - 0s 99us/sample - loss: 1.5671 - acc: 0.4534 - val_loss: 1.5646 - val_acc: 0.4536
Epoch 7/200
1557/1557 [==============================] - 0s 96us/sample - loss: 1.5504 - acc: 0.4534 - val_loss: 1.5478 

1557/1557 [==============================] - 0s 95us/sample - loss: 0.0501 - acc: 1.0000 - val_loss: 0.2309 - val_acc: 0.9401
Epoch 60/200
1557/1557 [==============================] - 0s 103us/sample - loss: 0.0463 - acc: 1.0000 - val_loss: 0.2277 - val_acc: 0.9416
Epoch 61/200
1557/1557 [==============================] - 0s 113us/sample - loss: 0.0429 - acc: 1.0000 - val_loss: 0.2255 - val_acc: 0.9416
Epoch 62/200
1557/1557 [==============================] - 0s 103us/sample - loss: 0.0398 - acc: 1.0000 - val_loss: 0.2235 - val_acc: 0.9416
Epoch 63/200
1557/1557 [==============================] - 0s 103us/sample - loss: 0.0370 - acc: 1.0000 - val_loss: 0.2214 - val_acc: 0.9416
Epoch 64/200
1557/1557 [==============================] - 0s 100us/sample - loss: 0.0345 - acc: 1.0000 - val_loss: 0.2200 - val_acc: 0.9416
Epoch 65/200
1557/1557 [==============================] - 0s 106us/sample - loss: 0.0322 - acc: 1.0000 - val_loss: 0.2173 - val_acc: 0.9431
Epoch 66/200
1557/1557 [==========

1557/1557 [==============================] - 0s 100us/sample - loss: 0.0041 - acc: 1.0000 - val_loss: 0.2109 - val_acc: 0.9461
Epoch 118/200
1557/1557 [==============================] - 0s 98us/sample - loss: 0.0040 - acc: 1.0000 - val_loss: 0.2110 - val_acc: 0.9461
Epoch 119/200
1557/1557 [==============================] - 0s 108us/sample - loss: 0.0039 - acc: 1.0000 - val_loss: 0.2112 - val_acc: 0.9461
Epoch 120/200
1557/1557 [==============================] - 0s 106us/sample - loss: 0.0038 - acc: 1.0000 - val_loss: 0.2114 - val_acc: 0.9461
Epoch 121/200
1557/1557 [==============================] - 0s 114us/sample - loss: 0.0037 - acc: 1.0000 - val_loss: 0.2116 - val_acc: 0.9461
Epoch 122/200
1557/1557 [==============================] - 0s 104us/sample - loss: 0.0036 - acc: 1.0000 - val_loss: 0.2118 - val_acc: 0.9461
Epoch 123/200
1557/1557 [==============================] - 0s 100us/sample - loss: 0.0035 - acc: 1.0000 - val_loss: 0.2120 - val_acc: 0.9461
Epoch 124/200
1557/1557 [===

1557/1557 [==============================] - 0s 95us/sample - loss: 0.0013 - acc: 1.0000 - val_loss: 0.2255 - val_acc: 0.9446
Epoch 176/200
1557/1557 [==============================] - 0s 104us/sample - loss: 0.0012 - acc: 1.0000 - val_loss: 0.2258 - val_acc: 0.9446
Epoch 177/200
1557/1557 [==============================] - 0s 103us/sample - loss: 0.0012 - acc: 1.0000 - val_loss: 0.2262 - val_acc: 0.9446
Epoch 178/200
1557/1557 [==============================] - 0s 103us/sample - loss: 0.0012 - acc: 1.0000 - val_loss: 0.2265 - val_acc: 0.9446
Epoch 179/200
1557/1557 [==============================] - 0s 103us/sample - loss: 0.0012 - acc: 1.0000 - val_loss: 0.2266 - val_acc: 0.9446
Epoch 180/200
1557/1557 [==============================] - 0s 105us/sample - loss: 0.0012 - acc: 1.0000 - val_loss: 0.2269 - val_acc: 0.9446
Epoch 181/200
1557/1557 [==============================] - 0s 104us/sample - loss: 0.0011 - acc: 1.0000 - val_loss: 0.2271 - val_acc: 0.9446
Epoch 182/200
1557/1557 [===

In [ ]:
xtr = train[700:]

In [ ]:
xla = label[700:]

In [123]:
xla

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [59]:
from sklearn.metrics import classification_report , confusion_matrix

In [60]:
pred = model.predict_classes(np.float32(test_padded))

In [61]:
pred

array([0, 2, 2, 4, 2, 0, 0, 1, 4, 4, 0, 0, 2, 3, 4, 1, 4, 1, 3, 3, 0, 0,
       0, 0, 2, 2, 0, 0, 4, 2, 4, 3, 2, 2, 4, 0, 3, 0, 1, 0, 4, 4, 0, 2,
       0, 4, 2, 3, 2, 0, 2, 1, 2, 3, 2, 1, 4, 0, 0, 0, 0, 3, 1, 2, 3, 0,
       2, 3, 2, 0, 1, 3, 1, 0, 4, 3, 4, 0, 1, 3, 2, 1, 0, 3, 2, 2, 3, 4,
       0, 4, 4, 3, 3, 4, 1, 2, 3, 0, 4, 3, 4, 0, 0, 4, 0, 3, 0, 3, 3, 1,
       1, 0, 0, 2, 2, 3, 1, 4, 3, 3, 2, 3, 3, 0, 3, 2, 3, 4, 1, 0, 1, 0,
       2, 2, 3, 2, 0, 2, 1, 2, 3, 2, 2, 0, 0, 0, 3, 3, 0, 0, 1, 2, 4, 3,
       3, 3, 2, 1, 0, 4, 2, 2, 1, 2, 2, 1, 0, 1, 3, 3, 2, 3, 3, 1, 4, 3,
       2, 0, 2, 1, 3, 0, 2, 4, 4, 3, 4, 1, 1, 2, 0, 2, 2, 3, 2, 3, 0, 4,
       0, 1, 3, 0, 3, 4, 4, 4, 2, 2, 4, 2, 0, 3, 0, 2, 2, 1, 0, 2, 1, 1,
       2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 2, 3, 4, 1, 0, 2, 2, 0, 0, 1, 0, 2,
       4, 4, 3, 2, 2, 0, 1, 0, 4, 2, 4, 3, 0, 2, 0, 3, 2, 2, 2, 3, 2, 0,
       4, 2, 2, 0, 3, 0, 2, 1, 3, 2, 0, 4, 0, 2, 2, 0, 2, 4, 1, 0, 3, 1,
       4, 1, 2, 1, 3, 3, 0, 1, 0, 4, 1, 0, 2, 1, 0,

In [62]:
preds= []
for i in pred:
    if(i == 0):
        preds.append([1 , 0 , 0 , 0 , 0])
    if(i == 1):
        preds.append([0 , 1 , 0 , 0 , 0])
    if(i == 2):
        preds.append([0 , 0 , 1 , 0 , 0])
    if(i == 3):
        preds.append([0 , 0 , 0 , 1 , 0])
    if(i == 4):
        preds.append([0 , 0 , 0 , 0 , 1])       

In [65]:
print(classification_report(test_labels , preds))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95       155
           1       0.99      0.90      0.94       117
           2       0.84      0.97      0.90       122
           3       0.99      0.99      0.99       153
           4       1.00      0.88      0.93       121

   micro avg       0.94      0.94      0.94       668
   macro avg       0.95      0.94      0.94       668
weighted avg       0.95      0.94      0.95       668
 samples avg       0.94      0.94      0.94       668



In [67]:
#0->Bussiness 1->Entertainment 2->Politics 3->Sport 4->Technology

In [134]:
random_news = ['manchester united will display banner declaring football nothing without fans clubs first match old trafford since resumption premier league amid coronavirus pandemic.the message, quoting former united manager sir matt busby, will placed stretford end wednesday evenings behind-closed doors clash sheffield united.in addition, stands will also contain mosaic featuring supporters countries celebration clubs diversity.executive vice chairman ed woodward sympathised fans unable attend matches due global health crisis predicted difficult months ahead.while everyone manchester united excited getting back playing football, regret fans cannot stadium, recognise difficult times many people around world woodward told united review.as banner stretford end tonight (wednesday) declares, quoting sir matt busby, football nothing without fans, cant wait return old trafford soon safe so.on pitch, no escaping reality coming months going difficult everyone football no exception.however, clubs foundations solid and, provided stick together manage resources carefully, will come period strength intact – thanks large part loyalty fantastic supportersole gunnar solskjaers fifth-placed side returned top-flight action 1-1 draw tottenham chase champions league qualification.the blades, also hold european aspirations, two points worse off ahead short trip across pennines']

In [140]:
random_news

['manchester united will display banner declaring football nothing without fans clubs first match old trafford since resumption premier league amid coronavirus pandemic.the message, quoting former united manager sir matt busby, will placed stretford end wednesday evenings behind-closed doors clash sheffield united.in addition, stands will also contain mosaic featuring supporters countries celebration clubs diversity.executive vice chairman ed woodward sympathised fans unable attend matches due global health crisis predicted difficult months ahead.while everyone manchester united excited getting back playing football, regret fans cannot stadium, recognise difficult times many people around world woodward told united review.as banner stretford end tonight (wednesday) declares, quoting sir matt busby, football nothing without fans, cant wait return old trafford soon safe so.on pitch, no escaping reality coming months going difficult everyone football no exception.however, clubs foundation

In [132]:
random_news = random_news.lower()

In [135]:
random_padded_seq = token.texts_to_sequences(random_news)

In [136]:
random_padded = pad_sequences(random_padded_seq , maxlen=120 , truncating='post')

In [137]:
ans = model.predict_classes(random_padded)

In [138]:
ans

array([3], dtype=int64)

In [139]:
#It predicted 3 i.e sport